// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<WPI_TalonSRX> drivetrainleftFront;
	static std::shared_ptr<WPI_TalonSRX> drivetrainleftRear;
	static std::shared_ptr<frc::SpeedControllerGroup> drivetrainleftDrive;
	static std::shared_ptr<WPI_TalonSRX> drivetrainrightFront;
	static std::shared_ptr<WPI_TalonSRX> drivetrainrightRear;
	static std::shared_ptr<frc::SpeedControllerGroup> drivetrainrightDrive;
	static std::shared_ptr<frc::DifferentialDrive> drivetrainDifferentialDrive;
	static std::shared_ptr<frc::Ultrasonic> drivetrainfrontUltrasonic;
	static std::shared_ptr<frc::Ultrasonic> drivetrainRearUltrasonic;
	static std::shared_ptr<WPI_TalonSRX> elevatorelevatorMotor;
	static std::shared_ptr<frc::DigitalInput> elevatorvaultPosSwitch;
	static std::shared_ptr<frc::DigitalInput> elevatorlowSwitchPosSwitch;
	static std::shared_ptr<frc::DigitalInput> elevatorhighSwitchPosSwitch;
	static std::shared_ptr<frc::DigitalInput> elevatorlowScalePosSwitch;
	static std::shared_ptr<frc::DigitalInput> elevatorhighScalePosSwitch;
	static std::shared_ptr<frc::DigitalInput> elevatorliftPointPosSwitch;
	static std::shared_ptr<frc::AnalogPotentiometer> elevatorposition_pot;
	static std::shared_ptr<WPI_TalonSRX> cubeIntakeleft_intake;
	static std::shared_ptr<WPI_TalonSRX> cubeIntakeright_intake;
	static std::shared_ptr<frc::DigitalInput> cubeIntakecubeInTrigger;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
