// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonomousCommand::AutonomousCommand(): frc::Command() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(Robot::chassis.get());
	Requires(Robot::drivetrain.get());
	timer = new frc::Timer();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	// Start the timer.
	this->timer->Start();
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	Robot::drivetrain->straightDrive(.5);
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	// See if we've traveled far enough.
	if (this->timer->Get() >= 6) {
		return true;
	}
	else {
		return false;
	}
}

// Called once after isFinished returns true
void AutonomousCommand::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {

}
